### PR TITLE
When a JMS message is received, traceId and spanId are not added to MDC of logger

### PR DESCRIPTION
**Pull request by lucapreziati**

### CODE REVIEW

**Comment by lucapreziati** [comment]
https://github.com/opentracing-contrib/java-jms/issues/26

**Comment by malafeev** [comment]
Why it should be added here?
It's not part of opentracing api. MDC,... whatever

**Comment by lucapreziati** [comment]
I think it is necessary because without this information in log is not
possible join the opentracing information with the trace in log.

I don't know if:
1) can be trasformed in optional like in web configuration
2) can be introduce something that can be consider an interceptor that
permit to implement/activate this custom option

Il giorno lun 15 lug 2019 alle ore 17:30 Sergei Malafeev <
notifications@github.com> ha scritto:

**Comment by malafeev** [comment]
> can be trasformed in optional like in web configuration

@lucapreziati could you provide a link to that?

I think slf4j dependency should be optional and MDC code should be under new configuration flag.

**Comment by lucapreziati** [comment]
@malafeev  i don't know how made a dependency optional, it is enough that has scope provided from your point of view?

For adding in logging i added this servlet filter.

```
public class TracingLogFilter implements Filter {

	@Autowired
	io.opentracing.Tracer tracer;

	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
			throws IOException, ServletException {
		SpanContext spanContext = getCurrentSpanContext();
		if (spanContext != null) {
			MDC.put("spanId", spanContext.toSpanId());
			MDC.put("traceId", spanContext.toTraceId());
		}
		chain.doFilter(request, response);
		if (spanContext != null) {
			MDC.remove("spanId");
			MDC.remove("traceId");
		}
	}

	private SpanContext getCurrentSpanContext() {
		if (tracer == null) {
			return null;
		} else if (tracer.activeSpan() == null) {
			return null;
		} else
			return tracer.activeSpan().context();
	}

}
```

**Comment by malafeev** [comment]
scope should be `optional`, but we need a  boolean parameter to enable/disable MDC

**Comment by malafeev** [comment]
@lucapreziati could you revert formatting? 
2 spaces are used for indentation (Google code style)

**Comment by lucapreziati** [comment]
@malafeev i will download and apply, sorry i forget to check. I have one more solid solution, if you are agree, which can meet you requirement of optional. Wait a secondo please, i am working on it.

**Comment by lucapreziati** [comment]
@malafeev do you think I can add in main pom the maven plugin to force to use google style formatter?

**Comment by malafeev** [comment]
thanks @lucapreziati 
could you also resolve conflicts?

**Comment by lucapreziati** [comment]
@malafeev sorry, there was a short down. I have created new repository. I will try the fix and i will propose a new pull request.

**Comment by lucapreziati** [comment]
@malafeev I suggest to close this merge request, i propose a solution more close to your requirement, having MDC by configuration.
The pull is https://github.com/opentracing-contrib/java-jms/pull/29

**Pull request closed without merging**
